- name: 'Check that rsyslog is installed'
  stat: path=/etc/rsyslog.conf
  register: rsyslog_conf
  tags:
    - rsyslog
    - files

- name: "Set PreserverFQDN on"
  lineinfile: >
    dest=/etc/rsyslog.conf
    regexp='^\$PreserveFQDN'
    line='$PreserveFQDN on'
    state=present
  when: rsyslog_conf.stat.exists|bool
  notify:
    - Restart rsyslog
  tags:
    - rsyslog
    - files

- name: "Set forwarding to logstash"
  lineinfile: >
    dest=/etc/rsyslog.conf
    regexp="^\*\.\* @{{ hostvars[logstash_forwarder]['private_ip']|default(hostvars[logstash_forwarder]['ansible_ssh_host']) }}:{{ logstash_syslog_port|default('514') }}"
    line="*.* @{{ hostvars[logstash_forwarder]['private_ip']|default(hostvars[logstash_forwarder]['ansible_ssh_host']) }}:{{ logstash_syslog_port|default('514') }}"
    state=present
  when: rsyslog_conf.stat.exists|bool and logstash_forwarder is defined
  notify:
    - Restart rsyslog
  tags:
    - rsyslog
    - files

- name: "Configure rsyslog for {{ caller_name }}"
  template: >
    src=roles/{{ caller_name }}/templates/rsyslog.conf.j2
    dest=/etc/rsyslog.d/{{ caller_name }}.conf
    mode=0644
    owner=root
    group=root
    backup=yes
  notify:
    - Restart rsyslog
  when: rsyslog_conf.stat.exists|bool
  tags:
    - rsyslog
    - files
